trigger:
  paths:
    include:
      - Dockerfile
      - azure-pipelines.yaml
  branches:
    include:
      - master
      - develop

variables:
  vmImage: "ubuntu-16.04"

  repository: "survivorbat/sentinel-scratch"
  uid: "1000"
  gid: "1000"

stages:
  - stage: BuildAndPublish
    displayName: Build and publish Image
    jobs:
      - job: BuildAndPublish
        displayName: Build and Publish image
        pool:
          vmImage: $(vmImage)
        matrix:
          v0.14.4:
            sentinel_version: 0.14.4
          v0.14.3:
            sentinel_version: 0.14.3
          v0.14.2:
            sentinel_version: 0.14.2
          v0.14.1:
            sentinel_version: 0.14.1
          v0.14.0:
            sentinel_version: 0.14.0
          v0.13.1:
            sentinel_version: 0.13.1
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(repository)
              arguments: --build-arg sentinel_version=$(sentinel_version) --build-arg uid=$(uid) --build-arg gid=$(gid)
              tags: |
                $(sentinel_version)
                latest
          - task: Docker@2
            displayName: Publish
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              containerRegistry: 'DockerHub'
              command: push
              repository: $(repository)
              tags: |
                $(sentinel_version)
                latest
