trigger:
  paths:
    include:
      - Dockerfile
      - azure-pipelines.yaml
  branches:
    include:
      - master
      - develop

variables:
  vmImage: "ubuntu-16.04"
  tag: $(Build.BuildId)
  repository: "sentinel-scratch"
  sentinel_version: "0.14.3"
  uid: "1000"
  gid: "1000"

stages:
  - stage: Build
    displayName: Build Image
    jobs:
      - job: Build
        displayName: Build Image
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(repository)
              arguments:
                sentinel_version: $(sentinel_vesion)
                uid: $(uid)
                gid: $(gid)
              tags: |
                $(tag)
                latest
  - stage: Publish
    displayName: Publish image
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Publish
        displayName: Publish Image
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Publish
            inputs:
              command: publish
              repository: $(repository)
              tags: |
                $(tag)
                latest
