trigger:
  paths:
    include:
      - Dockerfile
      - azure-pipelines.yaml
  branches:
    include:
      - master
      - develop

variables:
  vmImage: "ubuntu-16.04"
  tag: $(Build.BuildId)
  repository: "survivorbat/sentinel-scratch"
  sentinel_version: "0.14.3"
  uid: "1000"
  gid: "1000"

stages:
  - stage: Build
    displayName: Build Image
    jobs:
      - job: Build
        displayName: Build Image
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(repository)
              arguments: --build-arg sentinel_version=$(sentinel_version) --build-arg uid=$(uid) --build-arg gid=$(gid)
              tags: |
                $(tag)
                latest
          - task: Docker@2
            displayName: Publish
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              command: push
              repository: $(repository)
              tags: |
                $(tag)
                latest
