trigger:
  tags:
    include:
      - "*.*.*"

variables:
  vmImage: "ubuntu-16.04"

  repository: "survivorbat/sentinel-scratch"
  uid: "1000"
  gid: "1000"

  # The tag will be the version
  sentinel_version: $(Build.SourceBranchName)

stages:
  - stage: BuildAndPublish
    displayName: Build and publish Image
    jobs:
      - job: BuildAndPublish
        displayName: Build and Publish image
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(repository)
              arguments: --build-arg sentinel_version=$(sentinel_version) --build-arg uid=$(uid) --build-arg gid=$(gid)
              tags: |
                $(sentinel_version)
          - task: Docker@2
            displayName: Publish
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
            inputs:
              containerRegistry: 'DockerHub'
              command: push
              repository: $(repository)
              tags: |
                $(sentinel_version)
